# This compose file is run by Jenkins, so no static ports.
version: '3'

services:
  # We need a postgress server for VIP to initialize the database on.
  vip-postgres:
    image: docker.dbc.dk/dbc-postgres:10
    environment:
      # Note, if you change the databasename, you must update the run-system-test script, that loads some data
      # into the database. This could probably be avoided by using this image smarter.
      - POSTGRES_DB=vip_db
      - POSTGRES_USER=vip_user
      - POSTGRES_PASSWORD=vip_password
    expose:
      - 5432
    ports:
      - 5432

  # And, an vip image to populate the database (and, that is all it does, folks).
  # Note, that we depend on the latest build on master always. You will need
  # to change this yourself, if you need to do otherwise, e.g. during testing.
  vip-core:
    image: docker-i.dbc.dk/vipcore:latest
    expose:
      - 8080
    ports:
      - 8080
    environment:
      - DB_URL=vip_user:vip_password@vip-postgres:5432/vip_db
      - JAVA_MAX_HEAP_SIZE=2G
      - CACHE_VIPCORE=1
      - CACHE_FORS=1
      - FORSRIGHT_ENDPOINT=https://forsrights.addi.dk/1.2/

  # The image under test
  openagency-php:
    image: openagency-php-local/openagency-php${DOCKER_IMAGE_TAG}
    environment:
      - VIP_CREDENTIALS=psql://vip_user:vip_password@vip-postgres:5432/vip_db
      # This is maintained if we need testing of the postgresql parsing thing.
      # - VIP_CREDENTIALS=host=vip-postgres port=5432 dbname=vip_db user=vip_user password=vip_password connect_timeout=1
      - URL_PATH=staging_2.34
      - FORS_RIGHTS=https://forsrights.addi.dk/1.2/?action=forsRights&outputType=php&userIdAut=%s&groupIdAut=%s&passwordAut=%s&ipAddress=%s
      - APACHE_SERVER_NAME=localhost
      #- HTTP_PROXY=http://borchk-hoverfly:8500
      #- HTTP_PROXY_INSECURE_MODE_FOR_TEST_ONLY=1
      - COPA_RS_URL=https://iso18626.addi.dk/copa-rs/app/iso18626/
      - COPA_RS_PASSWD=xxxxxxxxxxxx
    expose:
      - 80
    ports:
      - 80

  # Debug container - will open for ports internally, on fixed ports
  debug:
    image: docker-i.dbc.dk/debug-container
    ports:
      - "5432:5432"
      - "8080:8080"
      # - "8081:8081"
    environment:
      FORWARD_VIP_DB: 'localhost:5432 to vip-postgres:5432 as Access to VIP test DB'
      FORWARD_OPENAGENCY: 'localhost:8080 to openagency-php:80 as Access to openagency-php http'
      # FORWARD_VIP: 'localhost:8081 to vip-core:8080 as Access to VIP http'


