# This compose file is run by Jenkins, so no static ports.
version: '3.3'

services:
  # We need a postgress server for VIP to initialize the database on.
  vip-postgres:
    image: docker-i.dbc.dk/vip-dit-test-data
    expose:
      - 5432
    ports:
      - 5432

  # And, an vip image to populate the database (and, that is all it does, folks).
  # Note, that we depend on the latest build on master always. You will need
  # to change this yourself, if you need to do otherwise, e.g. during testing.

  # The image under test
  openagency-php:
    image: openagency-php-local/openagency-php${DOCKER_IMAGE_TAG}
    environment:
      - VIP_CREDENTIALS=psql://vip:vippass@vip-postgres:5432/vip_db
      - URL_PATH=test_oa
      - FORS_RIGHTS=https://forsrights.addi.dk/1.2/?action=forsRights&outputType=php&userIdAut=%s&groupIdAut=%s&passwordAut=%s&ipAddress=%s
      - APACHE_SERVER_NAME=localhost
      - COPA_RS_URL=https://iso18626.addi.dk/copa-rs/app/iso18626/
      - COPA_RS_PASSWD=xxxxxxxxxxxx
    depends_on:
      - "vip-postgres"
    expose:
      - 80
    ports:
      - 80


  openagency-gold:
    image: docker-i.dbc.dk/openagency-php:133
    environment:
    - VIP_CREDENTIALS=psql://vip:vippass@vip-postgres:5432/vip_db
    - URL_PATH=gold_oa
    - FORS_RIGHTS=https://forsrights.addi.dk/1.2/?action=forsRights&outputType=php&userIdAut=%s&groupIdAut=%s&passwordAut=%s&ipAddress=%s
    - APACHE_SERVER_NAME=localhost
    - COPA_RS_URL=https://iso18626.addi.dk/copa-rs/app/iso18626/
    - COPA_RS_PASSWD=xxxxxxxxxxxx
    depends_on:
    - "vip-postgres"
    expose:
    - 80
    ports:
    - 80


