#!/usr/bin/env bash

function updateCherryPicks() {
    for FILE in ${OA_234_DIFF_LIST} ; do
      info "Updating '${FILE}' to revision '${OA_234_DIFF_REV}'"
      svn -q up -r ${OA_234_DIFF_REV}  ${FILE} || die "Unable to update '${FILE}' to revision '${OA_234_DIFF_REV}'"
    done
}

which dirname &> /dev/null || die "Unable to run dirname command - please install it"
export SCRIPTNAME="bootstrap"
export SCRIPT_DIR=$(dirname "$(readlink -f "$0")") || { echo "Unable to identify basedir from $0" ; exit 1; }
. "${SCRIPT_DIR}/shared.sh" || { echo "Unable to load shared file shared.sh" ; exit 1; }


# Get (or update) the svn externals needed by Borchk.
SVNREPO="https://svn.dbc.dk/repos/php/OpenLibrary/class_lib/trunk"
EXTNAME="OLS_class_lib"
OA_234_REV="117239" # = Oracle OpenAgency 2.34 version
OA_234_DIFF_REV="124699" # = PostgreSQL OpenAgency 2.34 version
OA_234_DIFF_LIST="pg_database_class.php pg_wrapper_class.php verbose_json_class.php"

set -e

check_on_path svn

SRCDIR="${PROJECT_DIR}/src"

cd "${SRCDIR}" || die "Unable to change directory to ${SRCDIR}"
if [ -d ${EXTNAME} ] ; then
    cd ${EXTNAME} || die "Unable to change directory to ${SRCDIR}/${EXTNAME}"
    info "Updating svn repo in '${SRCDIR}/${EXTNAME}'"
    svn -q up -r ${OA_234_REV} || die "Error when updating svn repo in '${SRCDIR}/${EXTNAME}'"
    updateCherryPicks
    info "Svn repo in '${SRCDIR}/${EXTNAME}' updated"
else
    info "Checking out svn repo '${SVNREPO}' into directory '${SRCDIR}/${EXTNAME}'"
    svn -q checkout -r ${OA_234_REV} ${SVNREPO} ${EXTNAME} || die "Unable to checkout svn repo '${SVNREPO}' into directory '${SRCDIR}/${EXTNAME}'"
    info "Svn repo '${SVNREPO}' revision '${OA_234_REV}' checked out into directory '${SRCDIR}/${EXTNAME}'"
    cd ${EXTNAME} || die "Unable to change into directory '${SRCDIR}/${EXTNAME}'"
    updateCherryPicks
fi
info "Svn info:"
svn info | grep -e Revision -e Last
