#!/usr/bin/env bash

# This is the kind of thing you would wish you did not have to do.
# We need the OLS class lib in a version that matches the original 2.34 deploy.
# But, we also need some fixes that are only available in the newest versions.
# The original fixed version we need is called ${OA_234_REV} in the following.
# (This has been branched out).
# And, then we need some additional files from a later revision.
# And, then we need a newer version on a branch of the abstract server.
# Please do not judge us based on this. Have pity. Relish the fact that you
# did not have to conjure this up.

# (Why did we not just copy it all - because that is a non-practical branch solution as the OLS_class_lib
# may suddenly have stuff we need. Okay, but why not merge newer stuff into another branch - we may
# do this at some point - but we fear the pain of svn merge. For now, this is what we have.)
# Appreciate what git has given us.

which dirname &> /dev/null || die "Unable to run dirname command - please install it"
export SCRIPTNAME="bootstrap"
export SCRIPT_DIR=$(dirname "$(readlink -f "$0")") || { echo "Unable to identify basedir from $0" ; exit 1; }
. "${SCRIPT_DIR}/shared.sh" || { echo "Unable to load shared file shared.sh" ; exit 1; }


# Get (or update) the svn externals needed by OpenAgency.
SVNREPO="https://svn.dbc.dk/repos/php/OpenLibrary/class_lib/trunk"
EXTNAME="OLS_class_lib"

set -e

check_on_path svn

SRCDIR="${PROJECT_DIR}/src"

cd "${SRCDIR}" || die "Unable to change directory to ${SRCDIR}"
if [ -d ${EXTNAME} ] ; then
    cd ${EXTNAME} || die "Unable to change directory to ${SRCDIR}/${EXTNAME}"
    info "Updating svn repo in '${SRCDIR}/${EXTNAME}'"
    svn -q up || die "Error when updating svn repo in '${SRCDIR}/${EXTNAME}'"
    info "Svn repo  updated"
    info "Svn repo in '${SRCDIR}/${EXTNAME}' updated"
else
    info "Checking out svn repo '${SVNREPO}' into directory '${SRCDIR}/${EXTNAME}'"
    svn -q checkout ${SVNREPO} ${EXTNAME} || die "Unable to checkout svn repo '${SVNREPO}' into directory '${SRCDIR}/${EXTNAME}'"
    info "Svn repo '${SVNREPO}' checked out into directory '${SRCDIR}/${EXTNAME}'"
fi
cd "${SRCDIR}/${EXTNAME}"
info "Svn info:"
svn info | grep -e URL -e Revision -e Last
