#!/usr/bin/env bash

# Tries to start a browser, if an opensearch server is currently running using docker compose.

which dirname &> /dev/null || die "Unable to run dirname command - please install it"
export SCRIPTNAME="client"
export SCRIPT_DIR=$(dirname "$(readlink -f "$0")") || { echo "Unable to identify basedir from $0" ; exit 1; }
. "${SCRIPT_DIR}/shared.sh" || { echo "Unable to load shared file shared.sh" ; exit 1; }

set -e

# Get information about the exposed port of the service from the compose file.
port=$(get_compose_service_port ${PROJECT_DIR}/docker/compose/systemtest/docker-compose.yml openagency-php 80)
URL="http://localhost:${port}/"

# Try to find a browser-open program
URL_OPEN_PROG=$(which xdg-open || which gnome-open || which kde-open || which firefox || which chromium-browser || which chrome || which links)

debug "Found URL opener to ${URL_OPEN_PROG}"

info "Starting ws client on ${URL}"
${URL_OPEN_PROG} ${URL} || die "Unable to start a client for url ${URL_OPEN_PROG}"
